TOOLCHAIN=../zyxel-keenetic-custom/zyxel-keenetic-packages/staging_dir/toolchain-mipsel_r2_gcc-4.1.2_uClibc-0.9.30.3
export PATH:=$(TOOLCHAIN)/bin:$(PATH)
CC=mipsel-openwrt-linux-uclibc-gcc
CFLAGS?=-O -s
LIBS=`[ \`uname\` = "SunOS" ] && echo -lsocket -lnsl`

.PHONY: all clean

all: darkhttpd

darkhttpd: darkhttpd.c
	$(CC) $(CFLAGS) $(LIBS) darkhttpd.c -o $@

clean:
	rm -f darkhttpd core darkhttpd.core
